"""added time info to job listings

Revision ID: 1106d0197057
Revises: d783a0024c1c
Create Date: 2026-01-14 11:01:47.862170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1106d0197057"
down_revision: Union[str, Sequence[str], None] = "d783a0024c1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "job_listings",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "job_listings",
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "job_listings",
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.execute("UPDATE job_listings SET created_at = NOW() WHERE created_at IS NULL")
    op.execute(
        "UPDATE job_listings SET last_updated_at = NOW() WHERE last_updated_at IS NULL"
    )
    op.execute(
        "UPDATE job_listings SET last_seen_at = NOW() WHERE last_seen_at IS NULL"
    )

    op.alter_column("job_listings", "created_at", nullable=False)
    op.alter_column("job_listings", "last_updated_at", nullable=False)
    op.alter_column("job_listings", "last_seen_at", nullable=False)

    op.alter_column("job_listings", "created_at", server_default=sa.text("NOW()"))
    op.alter_column("job_listings", "last_updated_at", server_default=sa.text("NOW()"))
    op.alter_column("job_listings", "last_seen_at", server_default=sa.text("NOW()"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_listings", "last_seen_at")
    op.drop_column("job_listings", "last_updated_at")
    op.drop_column("job_listings", "created_at")
    # ### end Alembic commands ###
