"""added warning and error counts and end reason to scrape reports

Revision ID: 11a5d32c815e
Revises: 296bdf077529
Create Date: 2026-01-15 16:24:39.195645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a5d32c815e'
down_revision: Union[str, Sequence[str], None] = '296bdf077529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_reports', sa.Column('warnings_count', sa.Integer(), nullable=False))
    op.add_column('scrape_reports', sa.Column('errors_count', sa.Integer(), nullable=False))
    op.add_column('scrape_reports', sa.Column('end_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_reports', 'end_reason')
    op.drop_column('scrape_reports', 'errors_count')
    op.drop_column('scrape_reports', 'warnings_count')
    # ### end Alembic commands ###
