"""added source website column to job listings

Revision ID: 296bdf077529
Revises: 955bb10a098a
Create Date: 2026-01-14 16:58:54.299081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296bdf077529'
down_revision: Union[str, Sequence[str], None] = '955bb10a098a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listings', sa.Column('source_website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_listings', 'source_website')
    # ### end Alembic commands ###
