"""updated job_listing indexing

Revision ID: 43f77bc56d9a
Revises: 651580db4e7e
Create Date: 2026-01-19 13:50:14.678626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f77bc56d9a'
down_revision: Union[str, Sequence[str], None] = '651580db4e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_job_listings_country'), 'job_listings', ['country'], unique=False)
    op.create_index(op.f('ix_job_listings_home_office'), 'job_listings', ['home_office'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_listings_home_office'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_country'), table_name='job_listings')
    # ### end Alembic commands ###
