"""added home office data to job listings

Revision ID: 651580db4e7e
Revises: c1bd7e7fe5c9
Create Date: 2026-01-17 16:19:21.465732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651580db4e7e'
down_revision: Union[str, Sequence[str], None] = 'c1bd7e7fe5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listings', sa.Column('home_office', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_listings', 'home_office')
    # ### end Alembic commands ###
