"""Updated job listing skills to cascade on delete

Revision ID: 849398e18452
Revises: 44920062b381
Create Date: 2026-01-05 22:37:46.673109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "849398e18452"
down_revision: Union[str, Sequence[str], None] = "44920062b381"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("job_listing_skills_skill_id_fkey"),
        "job_listing_skills",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("job_listing_skills_job_listing_id_fkey"),
        "job_listing_skills",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "job_listing_skills", "skills", ["skill_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "job_listing_skills",
        "job_listings",
        ["job_listing_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "job_listing_skills", type_="foreignkey")
    op.drop_constraint(None, "job_listing_skills", type_="foreignkey")
    op.create_foreign_key(
        op.f("job_listing_skills_job_listing_id_fkey"),
        "job_listing_skills",
        "job_listings",
        ["job_listing_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("job_listing_skills_skill_id_fkey"),
        "job_listing_skills",
        "skills",
        ["skill_id"],
        ["id"],
    )
    # ### end Alembic commands ###
