"""added scrape reports table

Revision ID: 955bb10a098a
Revises: 1106d0197057
Create Date: 2026-01-14 12:41:04.191528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '955bb10a098a'
down_revision: Union[str, Sequence[str], None] = '1106d0197057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_website', sa.String(), nullable=False),
    sa.Column('scrape_started_at', sa.DateTime(), nullable=True),
    sa.Column('scrape_finished_at', sa.DateTime(), nullable=True),
    sa.Column('total_jobs_scraped', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_reports_id'), 'scrape_reports', ['id'], unique=False)
    op.alter_column('job_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_listings', 'last_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_listings', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_listings', 'last_seen_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_listings', 'last_updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_listings', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_scrape_reports_id'), table_name='scrape_reports')
    op.drop_table('scrape_reports')
    # ### end Alembic commands ###
