"""added company to job listings

Revision ID: d783a0024c1c
Revises: f346b1c6582c
Create Date: 2026-01-14 10:31:14.771405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd783a0024c1c'
down_revision: Union[str, Sequence[str], None] = 'f346b1c6582c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listings', sa.Column('company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_listings', 'company')
    # ### end Alembic commands ###
