"""added country to job listings

Revision ID: f346b1c6582c
Revises: 520c7818c3e2
Create Date: 2026-01-12 12:57:53.025800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f346b1c6582c'
down_revision: Union[str, Sequence[str], None] = '520c7818c3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_listings', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_listings', 'country')
    # ### end Alembic commands ###
