"""Add category to skills and make job url unique

Revision ID: f61f8076e0d3
Revises: 1cd9f24fb392
Create Date: 2026-01-04 12:58:54.474371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f61f8076e0d3"
down_revision: Union[str, Sequence[str], None] = "1cd9f24fb392"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "job_listings", ["url"])
    op.add_column("skills", sa.Column("category", sa.String(), nullable=False))
    op.create_index(op.f("ix_skills_category"), "skills", ["category"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skills_category"), table_name="skills")
    op.drop_column("skills", "category")
    op.drop_constraint(None, "job_listings", type_="unique")
    # ### end Alembic commands ###
