services:
  celery_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
      target: prod
    container_name: job-scraper-worker
    command: celery -A scheduler.app.celery worker --loglevel=info
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env.docker

  celery_beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
      target: prod
    container_name: job-scraper-beat
    command: celery -A scheduler.app.celery beat --loglevel=info
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env.docker

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
