"""updated saved filters table

Revision ID: 419ab2694fb3
Revises: 641175e54a44
Create Date: 2026-01-27 15:04:38.024465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419ab2694fb3'
down_revision: Union[str, Sequence[str], None] = '641175e54a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_filters', sa.Column('with_home_office_only', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_saved_filters_with_home_office_only'), 'saved_filters', ['with_home_office_only'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_filters_with_home_office_only'), table_name='saved_filters')
    op.drop_column('saved_filters', 'with_home_office_only')
    # ### end Alembic commands ###
