"""added favorite listings table and updated indexing

Revision ID: bf678fd6dbb5
Revises: 2ac3d51225d7
Create Date: 2026-01-20 14:57:43.765822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf678fd6dbb5'
down_revision: Union[str, Sequence[str], None] = '2ac3d51225d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorited_job_listings',
    sa.Column('job_listing_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_listing_id'], ['job_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_listing_id', 'user_id')
    )
    op.create_index(op.f('ix_favorited_job_listings_job_listing_id'), 'favorited_job_listings', ['job_listing_id'], unique=False)
    op.create_index(op.f('ix_favorited_job_listings_user_id'), 'favorited_job_listings', ['user_id'], unique=False)
    op.create_index(op.f('ix_job_listing_skills_job_listing_id'), 'job_listing_skills', ['job_listing_id'], unique=False)
    op.create_index(op.f('ix_job_listing_skills_skill_id'), 'job_listing_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_listing_skills_skill_id'), table_name='job_listing_skills')
    op.drop_index(op.f('ix_job_listing_skills_job_listing_id'), table_name='job_listing_skills')
    op.drop_index(op.f('ix_favorited_job_listings_user_id'), table_name='favorited_job_listings')
    op.drop_index(op.f('ix_favorited_job_listings_job_listing_id'), table_name='favorited_job_listings')
    op.drop_table('favorited_job_listings')
    # ### end Alembic commands ###
