"""added saved filters and saved filter skills tables

Revision ID: fcb93ab0e211
Revises: 9fed14ce192f
Create Date: 2026-01-25 14:40:35.489000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcb93ab0e211'
down_revision: Union[str, Sequence[str], None] = '9fed14ce192f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seniority', postgresql.ARRAY(postgresql.ENUM('junior', 'mid', 'senior', name='seniority_level', create_type=False)), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_filters_company'), 'saved_filters', ['company'], unique=False)
    op.create_index(op.f('ix_saved_filters_country'), 'saved_filters', ['country'], unique=False)
    op.create_index(op.f('ix_saved_filters_user_id'), 'saved_filters', ['user_id'], unique=True)
    op.create_table('saved_filter_skills',
    sa.Column('saved_filter_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['saved_filter_id'], ['saved_filters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('saved_filter_id', 'skill_id')
    )
    op.create_index(op.f('ix_saved_filter_skills_saved_filter_id'), 'saved_filter_skills', ['saved_filter_id'], unique=False)
    op.create_index(op.f('ix_saved_filter_skills_skill_id'), 'saved_filter_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_filter_skills_skill_id'), table_name='saved_filter_skills')
    op.drop_index(op.f('ix_saved_filter_skills_saved_filter_id'), table_name='saved_filter_skills')
    op.drop_table('saved_filter_skills')
    op.drop_index(op.f('ix_saved_filters_user_id'), table_name='saved_filters')
    op.drop_index(op.f('ix_saved_filters_country'), table_name='saved_filters')
    op.drop_index(op.f('ix_saved_filters_company'), table_name='saved_filters')
    op.drop_table('saved_filters')
    # ### end Alembic commands ###
