server {
    listen 80;
    server_name placeholder.com; #I dont have a domain name yet :(
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name placeholder.com;

    ssl_certificate /etc/letsencrypt/live/placeholder.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/placeholder.com/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/jobs/  {
        limit_req zone=api_limit burst=30 nodelay;
        
        proxy_pass http://api:8000;
        include /etc/nginx/include/_proxy_headers.conf;
        include /etc/nginx/include/_cache.conf;

    }

    location /api/skills/  {
        limit_req zone=api_limit burst=30 nodelay;
        proxy_pass http://api:8000;
        include /etc/nginx/include/_proxy_headers.conf;
        include /etc/nginx/include/_cache.conf;
    }

    location /api/ {
        limit_req zone=api_limit burst=30 nodelay;
        proxy_pass http://api:8000;
        include /etc/nginx/include/_proxy_headers.conf;
    }
}